### ISSUE TITLE
script fails

### ISSUE THREAD

**Issue by wildchld-ops** [superseb/multipass-k3s#11]
No server token given, generated server token: iizytxzu5etj4r3irtgn
No agent token given, generated agent token: akud5gjvscig6fu9f6cl
No name given, generated name: ext13m
Creating cluster ext13m with 1 server(s) and 1 agent(s)
Cloud-init is created at ext13m-init-cloud-init.yaml
Creating initial server instance: k3s-server-ext13m
Running multipass launch --cpus 2 --disk 5G --mem 1G focal --name k3s-server-ext13m --cloud-init ext13m-init-cloud-init.yaml
error: No such file: ext13m-init-cloud-init.yaml
There was an error launching the instance

Ubuntu 20.04 fresh install BM

**Comment by superseb** [comment]
No such file, do you have write permissions in the directory where you are executing the script? Can you share `bash -x multipass-k3s.sh`?

**Comment by wildchld-ops** [comment]
running it through git fails your droplet is working fine.
