### ISSUE TITLE
HA setup?

### ISSUE THREAD

**Issue by codeagencybe** [superseb/multipass-k3s#12]
Hello

I just found your script and was reading that it supports HA with embedded etcd. 
So I checked the script but got confused how the config is working

```
# How many additional server instances to create
SERVER_COUNT_MACHINE="0"
# How many agent instances to create
AGENT_COUNT_MACHINE="1"
```

I would like to spin up 3 masters and 3 workers. 

Do I understand correct that by default it only spin up 1 master? 
So if I put SERVER_COUNT_MACHINE="2", it will generate a total of 3 masters? 

And for the agent, I need to set it as AGENT_COUNT_MACHINE="3" ?

**Comment by superseb** [comment]
Yes that is correct, feel free to submit a PR where this is more clear or I will look at it in the weekend. It grew this way because embedded etcd wasn't available the first time this was created.

I also just merged a change to prevent a current issue in k3s regarding agent tokens.

**Comment by superseb** [comment]
Did it work for you @codeagencybe ?

**Comment by codeagencybe** [comment]
@superseb 
Sorry for not updating you! 
I wanted to try it but I got blocked by another problem from multipass or WSL itself. 
I'm running Windows 11 pro with WSL2 and Ubuntu, but for some odd reason, I can't install multipass in Ubuntu WSL2. 
It returns this output

`error: cannot communicate with server: Post http://localhost/v2/snaps/multipass: dial unix /run/snapd.socket: connect: no such file or directory
`

So I first have to fix this problem. Been searching for a solution the past days but haven't found anything yet. 
It seems to be an edge case with WSL specific.

**Comment by superseb** [comment]
@codeagencybe Did you get this to work?

**Comment by codeagencybe** [comment]
@superseb 
Nope, still not. Haven't found a single working clue on this. 
Meanwhile I have a raspberry pi running with Ubuntu 20.04 server as replacement. But if someone knows how to fix the wsl problem for snap, I still want to know

**Comment by superseb** [comment]
@codeagencybe Seems to be https://github.com/microsoft/WSL/issues/5126? But not a real solution, just plenty of workarounds in that issue.

**Comment by codeagencybe** [comment]
Tried many but not working. Most of these changes are also temporary. After rebooting PC/WSL it's gone and you have to reapply again. 
But I couldn't get it working at all. I think these hacky workarounds no longer work for current versions of WSL2. These temp hacks are dated 2020

**Comment by superseb** [comment]
Yeah it seems messy, only recent thing I could find was https://github.com/diddledani/one-script-wsl2-systemd.

As this is not something I can fix, I'm going to close this issue for now. Let me know if I can help if you run into anything else.
