### ISSUE TITLE
[Feature Request] Add an option to append the kubeconfig to default kubeconfig file

### ISSUE THREAD

**Issue by yeahdongcn** [superseb/multipass-k3s#15]
Thanks for creating such a great script, it works perfectly on my m1 mbp.
Is there possible to add an option to append the kubeconfig to the default kubeconfig file (e.g. ~/.kube/config on macOS)?

**Comment by superseb** [comment]
This would probably need a flag for the user to decide as it can't be changing files by default. But the intent of the script was to just setup a cluster with the configurable options, not really a list of flags.

I would automate this by using something like using ```KUBECONFIG=~/.kube/config:./xxxxx-kubeconfig.yaml kubectl  config view --flatten```, what we could add is creating a new file that stores the output of this command if `~/.kube/config` is found.

**Comment by superseb** [comment]
Let me know if this doesn't solve your issue.

**Comment by yeahdongcn** [comment]
So no automatic way will be provided, right? 😂

**Comment by superseb** [comment]
I can add an environment variable that does the above and backs up the current kubeconfig, if that would help your use case.

**Comment by yeahdongcn** [comment]
> I can add an environment variable that does the above and backs up the current kubeconfig, if that would help your use case.

Sounds great! Thanks in advance.

**Comment by superseb** [comment]
@yeahdongcn you can test it out with https://github.com/superseb/multipass-k3s/pull/17, make sure you backup your existing kubeconfig manually first.

**Comment by yeahdongcn** [comment]
Thanks @superseb it works like a charm.

It seems `$NAME-kubeconfig-backup.yaml` is created as a backup of the existing `kubeconfig`.
